### ISSUE TITLE
Geo region ids do not match data region ids

### ISSUE THREAD

**Issue by danse** [open-europe/mur#1]
For example in Germany there is `DE80J` and other `DE80<letter>` codes which do not exist in the data files. On the other hand data files reference region with `DE80<number>` which i did not find in the geographic file

**Comment by danse** [comment]
File were taken from [here](http://geoexamples.com/d3/2015/09/25/d3-EUROSTAT-topojson.html) and might be a bit outdated, i'll try to generate a fresh version of them

**Comment by danse** [comment]
@rveciana I hope you are fine with me asking some for some hints. I am trying to build a visualisation on top of your NUTS files and data from Eurostat. The region codes do not seem to match. I thought that the files could be outdated, but on the [Eurostat page](http://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units) i see that the last release of NUTS seems to be in 2013, so maybe the problem is a different one ... any clue?

**Comment by rveciana** [comment]
Hi Francesco,

I don't know if the NUTS regions codes changed. The last time I took a
look, some regions were added (I remember Turkey, for instance), but no
region was removed. Besides, the codes start with the country name, so it's
strange...

Do you know which regions are failing?

Roger


2017-03-06 14:19 GMT+01:00 Francesco Occhipinti <notifications@github.com>:

**Comment by danse** [comment]
Thanks for answering. Yes, i'm missing all of Turkey, many regions from Germany and Spain, and some other regions here and there. I was puzzled because on the Eurostat site, the last release is called NUTS 2013, but now i see that it was released in December 2015, thus after your post. Hopefully if i will follow your post and generate a recent version of the Topojson, things should work fine

**Comment by danse** [comment]
@rveciana if you want, we could keep an updated version of the NUTS Topojson in some repo on Github. I created `open-europe` as an organisation intended to maintain such kind of resources

**Comment by danse** [comment]
I actually saw that your example is using the 2013 version, which is the latest. I think that the problem was caused by the dataset referring to an older NUTS 3 schema. I tried with a more recent data set and it worked perfectly. Thanks for your support!

**Comment by rveciana** [comment]
Hi Francesco, this idea it's really interesting. An updated site with the
main regions layers in topojson or geojson formats would be great for many
people.
I'm glad that you found the solution

2017-03-13 15:32 GMT+01:00 Francesco Occhipinti <notifications@github.com>:
